- testNa.md
> test: test for brach -Na

- testNa.md
Reverts Binturong-GH/Grace-Shopper#1
> Revert "test: test for brach -Na"

- madeleine-test.md
> Test: Madeleine test merge

- coraTest.md
Here are may updates! Let me know if approved
> coras changes

- script/data/user.js
- server/db/index.js
- server/db/models/User.spec.js
- server/db/models/userModel.js
create our own user model which is userModel.js , change the old User model name to keep it there.
create script/data to store user dummy data
> Feat create user model

- server/db/models/Order.js
> Cora's Models

- script/seed.js
make changes in script/seed.js seed user dummy data
> feat(script):seed user dummy data

- server/db/models/productName.js
I have defined our Product sequelize model, let me know if you'd like any changes!
> feat: define Product model

- server/db/index.js
create relationship between models
> Feat define association

- package.json
set up our project name in order to create database for our project.
> feat(package.json):set project name to temporory grace-shopper

- script/data/product.js
- script/seed.js
- server/db/index.js
- server/db/models/orderModel.js
- server/db/models/productModel.js
Configured seed file and confirmed that it populates the main database
> feat: finished configuring seed file

- .gitignore
- config/keys.js
- package.json
- script/seed.js
- server/auth/authController.js
- server/auth/index.js
- server/db/models/userModel.js
- server/index.js
- test/server/models/userModel.spec.js
1. complete route: POST /auth/signup, which will create a new user and return token inside the response
2. create a test folder at the root directory, and write userModel.spec.js to test instance methods, hooks, and All test specs pass by run command: npm run mocha to test it.
> Feat test signup

- script/seed.js
- server/db/index.js
- server/db/models/cartModel.js
Reviewing our schema tonight, it seemed to me that we might need to add a "quantity" column to our chart table. Previously, we were creating it through sequelize magic methods, but in order to add an additional table, we'll need to create a model for that. I have done that here, and we can discuss and see if this approach makes sense.
> Update cart model

- server/api/index.js
- server/api/productRouter.js
- server/api/users.spec.js
- server/controllers/productController.js
- test/server/routes/product.spec.js
> coras all product & individual API's

- server/auth/authController.js
- server/auth/index.js
- server/db/models/userModel.js
- test/server/models/userModel.spec.js
- test/server/routes/authRoutes.spec.js
- test/server/routes/product.spec.js
1. pending the test specs of userModel.spec.tset
2. pending the test specs of product route
> Test pending user model test

- server/auth/authController.js
- server/auth/index.js
- server/db/models/userModel.js
- test/server/models/userModel.spec.js
- test/server/routes/authRoutes.spec.js
1. feat: add protect middleware that used to protect private resource
2. feat: enable /auth/me to get logged in user information 
3. write test specs to test userModel hook, class method and instance method 
4. write test specs to test protect resource: /auth/me
> Feat protect access

- server/auth/authController.js
- server/auth/index.js
- test/server/routes/authRoutes.spec.js
1. add restrictTo controller and /auth/isAdmin route as example of how to use this middleware
2. add test to test the /auth/isAdmin route, pass the test.
> Feat authorization

- client/app/AppRoutes.js
- client/app/pages/LoginPage.js
- client/app/pages/SignupPage.js
- client/app/store/slices/authSlice.js
- package.json
1. create auth slice 
2. create a signup page
3. add a dummy home page to test the auto nav functionality once user is logged in. 
4. change the backend response data, change it to include token and current login user data
> Feat user signup login at page

- client/app/components/CartList.js
- client/app/components/Navbar.js
- client/app/components/SingleProduct.js
- client/app/pages/Cart.js
- client/app/store/index.js
- client/app/store/slices/cartSlice.js
- client/app/store/slices/singleProductSlice.js
- client/index.js
- server/controllers/cartController.js
Cart functionality updated with the following:
- pulled in some of Cora's navbar code so that I could navigate between products and cart without refreshing
- added 'add to cart' button on product detail page for testing purposes (this can be removed or edited however people like, I just wanted to throw something on there so that I could test adding items to cart)
- the following cart methods are up and running in redux: add to cart, delete from cart, increase quantity, decrease quantity. note that these are just the redux methods--these changes are not currently going to the DB for registered users, and it is not being saved in local storage yet. 
- the cart page now shows some basic item details, as well as calculating subtotals and order total price.
> Cart slice

- client/app/components/CartList.js
- client/app/components/Navbar.js
- client/app/components/SingleProduct.js
- client/app/pages/Cart.js
- client/app/store/index.js
- client/app/store/slices/cartSlice.js
- client/app/store/slices/singleProductSlice.js
- client/index.js
- server/controllers/cartController.js
small bugfix to my cart branch that updates the logic for calculating cart totals
> Cart bugfix

- client/app/pages/Cart.js
- client/app/store/slices/cartSlice.js
- server/api/cartRouter.js
- server/api/index.js
- server/controllers/cartController.js
Updated all API routes for cart with help from Na. These have all been checked in Postman, and API documentation is available here: https://docs.google.com/document/d/1tSxujmw_eNV0cgis2e7fYX0m99woneMpQTX_e1AQ6y4/edit#
> Feat implement auth check for cart

- server/api/productRouter.js
- server/controllers/productController.js
- server/db/models/productModel.js
complete backend code of 
1. create a new product 
2. edit existed product
3. delete exist product
> Feat admin

- client/app/components/Navbar.js
- public/style.css
Hi Ladies, fixed one of the warnings for the Nav Bar.
> Nav Bar Warning Fixed

- client/app/components/SingleProduct.js
quick solve the error message when we do the merge conflict.
> fix: fix error of missing } at if statement

- client/app/components/ProductsList.js
1. add pagination to all products page, each page has 10 products
2. handle loading state when sending request to server
3. handle error state if axios request has been rejected.
> Allproducts pagination loading error handle

- client/app/AppRoutes.js
- client/app/components/PaymentForm.js
- client/app/pages/OrderDetailPage.js
- client/app/pages/PaymentPage.js
- client/app/store/index.js
- client/app/store/slices/orderSlice.js
- public/style.css
- server/api/index.js
- server/api/orderRouter.js
- server/controllers/orderController.js
- server/db/models/orderModel.js
Here is everything up and running so far for payment page
> Payment page continued

- client/app/components/Navbar.js
- client/app/components/ProductsList.js
- client/app/pages/ProductsListPage.js
- client/app/utils/paginate.js
1. add style layout to all products page
> Style all products with mui grid

- client/app/components/Navbar.js
- client/app/pages/ProductsListPage.js
- client/app/pages/UsersListPage.js
1. add spacing to admin users/products page
2. make text and icon to be white in navbar.
> Add style to admin page, and navbar 
